// <auto-generated />
using InterviewWebAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewWebAPI.Migrations
{
    [DbContext(typeof(InterviewDbContext))]
    partial class InterviewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewWebAPI.Context.Model.Vacancy", b =>
                {
                    b.Property<int>("VacancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacancyId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProposalCompensation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VacancyId");

                    b.ToTable("Vacancies");

                    b.HasData(
                        new
                        {
                            VacancyId = 1,
                            Description = "John",
                            ProposalCompensation = 30000m,
                            Title = "Developer"
                        },
                        new
                        {
                            VacancyId = 2,
                            Description = "Chris",
                            ProposalCompensation = 50000m,
                            Title = "Manager"
                        },
                        new
                        {
                            VacancyId = 3,
                            Description = "Mukesh",
                            ProposalCompensation = 20000m,
                            Title = "Consultant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
